apiVersion: v1
kind: Service
metadata:
  name: stackmap-wmts
spec:
  selector:
    app: stackmap-wmts
  ports:
  - name: "http"
    protocol: "TCP"
    port: 9099
    targetPort: 9099
  type: ClusterIP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wmts
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`stackmap.clouds.is`) && PathPrefix(`/services/projects/{[A-Za-z0-9_]+}/wmts`)
      kind: Rule
      services:
        - name: stackmap-wmts
          port: 9099

    - match: Host(`stackmap.clouds.is`) && PathPrefix(`/services/projects/{[A-Za-z0-9_]+}/products/{[A-Za-z0-9_]+}/leaflet`)
      kind: Rule
      services:
        - name: stackmap-wmts
          port: 9099

    - match: Host(`stackmap.clouds.is`) && PathPrefix(`/services/wmts`)
      kind: Rule
      services:
        - name: stackmap-wmts
          port: 9099
          
    - match: Host(`stackmap.clouds.is`) && PathPrefix(`/services/leaflet`)
      kind: Rule
      services:
        - name: stackmap-wmts
          port: 9099

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: wmts
#     #annotations:
#     #haproxy.org/path-rewrite: "/"
# spec:
#   #ingressClassName: haproxy
#   ingressClassName: traefik
#   rules:
#   - host: stackmap.clouds.is
#     http:
#       paths:
#       - path: /services/wmts
#         pathType: Prefix
#         backend:
#           service:
#             name: stackmap-wmts
#             port:
#               number: 9099
#       - path: /services/leaflet
#         pathType: Prefix
#         backend:
#           service:
#             name: stackmap-wmts
#             port:
#               number: 9099

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackmap-wmts
spec:
  selector:
    matchLabels:
      app: stackmap-wmts
  replicas: 1
  template:
    metadata:
      labels:
        app: stackmap-wmts
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: stackmap-wmts
        image: ghcr.io/eysteinn/stackmap-wmts:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9099

        env:
        - name: STACKMAP_API_SERVICE
          value: http://stackmap-api.default.svc.cluster.local:3000

        - name: WMS_HOST
          value: http://stackmap-mapserver.default.svc.cluster.local:6000


