apiVersion: v1
kind: Service
metadata:
  name: stackmap-wmts
spec:
  selector:
    app: stackmap-wmts
  ports:
  - name: "http"
    protocol: "TCP"
    port: 9099
    targetPort: 9099
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wmts
    #annotations:
    #haproxy.org/path-rewrite: "/"
spec:
  #ingressClassName: haproxy
  ingressClassName: traefik
  rules:
  - host: stackmap.clouds.is
    http:
      paths:
      - path: /services/wmts
        pathType: Prefix
        backend:
          service:
            name: stackmap-wmts
            port:
              number: 9099
      - path: /services/leaflet
        pathType: Prefix
        backend:
          service:
            name: stackmap-wmts
            port:
              number: 9099

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackmap-wmts
spec:
  selector:
    matchLabels:
      app: stackmap-wmts
  replicas: 1
  template:
    metadata:
      labels:
        app: stackmap-wmts
    spec:
      
      containers:
      - name: stackmap-wmts
        image: stackmap-wmts:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9099

        env:
        - name: STACKMAP_API_SERVICE
          value: http://stackmap-api.default.svc.cluster.local:3000
        - name: WMS_HOST
          value: http://stackmap-mapserver.default.svc.cluster.local:6000


