#
name: Deploy to DEV

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [Push to GHCR]
    types:
      - completed
      
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEV_SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.DEV_SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -p ${{ secrets.DEV_PORT }} -H ${{ secrets.DEV_IP }} >> ~/.ssh/known_hosts
      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.DEV_USER_IP }} -p ${{ secrets.DEV_PORT }} -- "kubectl delete deploy $REPO; kubectl apply -f $DEP"
        env:
          DEP: https://raw.githubusercontent.com/${{ github.repository }}/main/deployment.yaml
          REPO: ${{ github.event.repository.name }}
          
